server:
  port: 8761
  ip: 127.0.0.1
spring:
  application:
    name: nasi-eureka-server
  security:
    user:
      name:
      password:

eureka:
  instance:
    ip-address: ${server.ip}
    prefer-ip-address: false
    instance-id: ${server.ip}:${spring.application.name}:${server.port}
    hostname:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${server.ip}:${server.port}/eureka/

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS